rules:
  drop:
    - span_kind: SERVER
      attributes:
        - url.path:
            - ^/health$
            - ^/metrics$
        - http.route:
            - ^/health$
            - ^/mad$
    - span_kind: CLIENT
      attributes:
        - bac.def:
            - ^/health$
            - ^/metrics$
        - lm.rd:
            - ^/rod$
            - ^/cad$
