receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
#  logging:
#    verbosity: detailed # Ensure logging exporter is defined
  file:
    path: /tmp/otel-data/traces.log

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
#      exporters: [debug]